### ISSUE TITLE
Buttons on SpaceMouse Enterprise do nothing

### ISSUE THREAD

**Issue by dyaso** [FreeSpacenav/spacenavd#45]
The [device has 31 buttons](https://3dconnexion.com/uk/product/spacemouse-enterprise/#start) which don't currently do anything. 

If at least the Shift and Control keys could be made to work that'd help me a lot, but I have no idea how to help -- I've tried running `xev` but no events seem to be sent.

**Comment by jtsiomb** [comment]
libspnav comes with an example program (`libspnav/examples/simple`) which prints all the events received by spacenavd. You can use that to test the buttons, and to Use that to test the buttons, and to figure out which button corresponds to which number, so that you can set up key mappings in `/etc/spnavrc`. See the example configuration file (`spacenavd/doc/example-spnavrc`) the section starting with "Map buttons to keyboard keys".

**Comment by dyaso** [comment]
Thanks for your help!

When I make a remapping in `/etc/spnavrc` it doesn't do anything, but the button stops being reported as pressed by the `examples/simple_af_unix` program.

**Comment by jtsiomb** [comment]
Yes of course that's significant. If spacenavd can't connect to the X server, then it can't send keyboard events. Also the UNIX socket protocol will work (`simple_af_unix`) but the X11-based protocol won't (`simple_x11`). See FAQ number 10: http://spacenav.sourceforge.net/faq.html#faq10

**Comment by dyaso** [comment]
Apologies for not having read the FAQ, and wasting your time. Button remapping works now, barring several buttons which all identify as #0.

How plausible would it be to have buttons send Ctrl+Z / Shift+Ctrl+Z key combinations with a single press? I realize I'd probably have to modify `spacenavd` somewhere.

**Comment by jtsiomb** [comment]
It's not possible currently to send multiple key events, but there's no reason why it couldn't be done. If you wish open a feature request (marked enhancement) about it.
