### ISSUE TITLE
provide systemd service

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/spacenavd#61]
Basically

/etc/systemd/system/spacenavd.service
```
[Unit]
Description=Userspace Daemon of the spacenav driver.

[Service]
Type=forking
PIDFile=/var/run/spnavd.pid
Environment=XAUTHORITY=/run/user/1000/gdm/Xauthority
ExecStart=/usr/bin/spacenavd

[Install]
WantedBy=multi-user.target
```

it can be added to install step

from https://wiki.archlinux.org/title/3D_Mouse

**Comment by albfan** [comment]
hmm, it is on https://github.com/FreeSpacenav/spacenavd/blob/master/contrib/systemd/spacenavd.service

just needs to be installed providing some option. `--with-systemd` ?

**Comment by jtsiomb** [comment]
The systemd service file is an unsupported 3rd party contribution (hence the `contrib` directory). The only reason to include it in spacenavd at all is because it might be helpful to people trying to set up spacenavd on systems using systemd init, mainly as an example. Adding an option to install it would imply a certain degree of assurance of correctness and maintainability which I'm not comfortable with.

Even the SysV init file which I've written myself is not installed by default, without an extra explicit step, as it might need modifications for different systems.
