### ISSUE TITLE
systemctl status spacenavd

### ISSUE THREAD

**Issue by Nimingez** [FreeSpacenav/spacenavd#96]
I can not find the mouse
(suite) nmz@nmz-desktop:~/robosuite/robosuite/demos$ systemctl status spacenavd
● spacenavd.service - 3Dconnexion Input Devices Userspace Driver
     Loaded: loaded (/lib/systemd/system/spacenavd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-02-28 11:17:25 CST; 2min 42s ago
   Main PID: 1043 (spacenavd)
      Tasks: 1 (limit: 76703)
     Memory: 984.0K
     CGroup: /system.slice/spacenavd.service
             └─1043 /usr/bin/spacenavd -d -v

2月 28 11:17:41 nmz-desktop spacenavd[1043]: already using device: 3Dconnexion SpaceMouse Wireless (/dev/input/event3)
2月 28 11:17:41 nmz-desktop spacenavd[1043]: failed to find any supported devices

**Comment by jtsiomb** [comment]
"I cannot find the mouse" is extremely vague.

Run the `simple_af_unix` example program which come with libspnav under `examples/simple`, or `spnavcfg`. If either of those work and respond to input from the device, then the device is picked up fine by spacenavd, as the "already using device" line  would imply. If not, then post the contents of `/var/log/spnavd.log`. Remove the `-d` option from the service file so that spacenavd will daemonize properly and use the log file instead of printing to the console.

**Comment by jtsiomb** [comment]
Assuming this is no longer an issue, since the OP didn't respond for months.

**Comment by Nimingez** [comment]
![image](https://github.com/FreeSpacenav/spacenavd/assets/104558844/0fd1ed6c-8508-4956-a300-ae89822c39ea)

**Comment by jtsiomb** [comment]
That's some python error. It doesn't have anything to do with spacenavd.
